

server:
  port: 8881



spring:
  mvc:
    static-path-pattern: /static/**
  datasource:
    url:  jdbc:mysql://106.14.237.78:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 1hbl#QThztwcs
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      initial-size: 5
      max-idle: 10
      min-idle: 6
      max-wait-millis: 10000


mybatis:
  type-aliases-package: com.robin.demoproject.bean
  mapper-locations:
    - classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl